{% set name = "botocore-stubs" %}
{% set version = "1.24.18" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/botocore-stubs-{{ version }}.tar.gz
  sha256: 25074f7d7fbc5436e7060f5adbd8b9cf16f5ec601212725d63eb1386673f2f48

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.6
  run:
    - python >=3.6
    - typing_extensions

test:
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/vemel/mypy_boto3_builder
  summary: Type annotations for botocore.
  dev_url: https://github.com/vemel/mypy_boto3_builder
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
