{% set name = "botocore-stubs" %}
{% set version = "1.27.47" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/botocore-stubs-{{ version }}.tar.gz
  sha256: 378a35618d8abbcdc23436139d8315f9ac23db5a76a85d99458a52cb964b09ff

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.6
  run:
    - python >=3.6
    - types-awscrt
    - typing_extensions

test:
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/vemel/mypy_boto3_builder
  summary: Type annotations for botocore.
  dev_url: https://github.com/vemel/mypy_boto3_builder
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
